name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: Kholoud-fares
password: kholoud1337378189
- name: Build the hello-docker Docker image
run: |
       docker build . --tag https://github.com/Kholoud-fares/dockerImage.git
       docker run https://github.com/Kholoud-fares/dockerImage.git
       docker push https://github.com/Kholoud-fares/dockerImage.git
